export enum EnumerationType {
   PROJECTTYPE='PROJECTTYPE',
   PROJECTSTATUS='PROJECTSTATUS',
   EXPANSEITEMTYPE = 'EXPANSEITEMTYPE',
   EXPANSEITEM = 'EXPANSEITEM', 
   TRANSACTIONTYPE = 'TRANSACTIONTYPE'
}
